import { Dictionary } from './types'
export const DICTIONARIES: Record<string, Dictionary> = {
    default: {
        title: 'World cup',
        subtitle: 'Round of 16',
        greet: 'Hello!',
        team: 'Team',
        points: 'Pts',
        won: 'W',
        drawn: 'D',
        lost: 'L',
        gd: 'GD',
    },
    kor: {
        title: '월드컵 16강',
        subtitle: '',
        greet: '안녕하세요!',
        team: '팀',
        points: '승점',
        won: '승',
        drawn: '무',
        lost: '패',
        gd: '득실',
    },
    usa: {
        title: 'World cup',
        subtitle: 'Round of 16',
        greet: 'Hello!',
        team: 'Team',
        points: 'Points',
        won: 'Won',
        drawn: 'Drawn',
        lost: 'Lost',
        gd: 'Goals difference',
    },
    esp: {
        title: 'Copa Mundial',
        subtitle: 'Octavos De Final',
        greet: '¡Hola!',
        team: 'Team',
        points: 'Points',
        won: 'Won',
        drawn: 'Drawn',
        lost: 'Lost',
        gd: 'Goals difference',
    },
    fra: {
        title: 'Coupe du monde',
        subtitle: '16es de finale',
        greet: 'Bonjour!',
        team: 'Team',
        points: 'Points',
        won: 'Won',
        drawn: 'Drawn',
        lost: 'Lost',
        gd: 'Goals difference',
    },
    jpn: {
        title: 'ワールドカップ 16強',
        subtitle: '',
        greet: 'こんにちは!',
        team: 'Team',
        points: 'Points',
        won: 'Won',
        drawn: 'Drawn',
        lost: 'Lost',
        gd: 'Goals difference',
    },
    // qat: {
    //     title: 'كأس العالم',
    //     subtitle: 'دور الـ16',
    //     greet: 'أهلا',
    //     team: 'فريق',
    //     points: 'Points',
    //     won: 'Won',
    //     drawn: 'Drawn',
    //     lost: 'Lost',
    //     gd: 'Goals difference',
    // },
}
